{% set name = "top2vec" %}
{% set version = "1.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/top2vec-{{ version }}.tar.gz
  sha256: 3fcaf3b78aa44c09a6ba5b29dc2757630f87782faf35a63d518c9310177e4e3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cython
    - gensim <4.0.0
    - fuzzytm
    - hdbscan >=0.8.27
    - numpy >=1.20.0
    - pandas
    - python >=3.6
    - umap-learn >=0.5.1
    - wordcloud


test:
  imports:
    - top2vec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ddangelov/Top2Vec
  summary: Top2Vec learns jointly embedded topic, document and word vectors.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - llperez
