{% set name = "top2vec" %}
{% set version = "1.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/top2vec-{{ version }}.tar.gz
  sha256: 8bfe6fa8f72202d51f5068cb0d4eee2095a098a56bf46b2b5d2365319e651ce8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cython
    - gensim <4.0.0
    - hdbscan >=0.8.27
    - numpy >=1.20.0
    - pandas
    - python >=3.6
    - umap-learn >=0.5.1
    - wordcloud

test:
  imports:
    - top2vec
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ddangelov/Top2Vec
  summary: Top2Vec learns jointly embedded topic, document and word vectors.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - llperez
